name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4 #Retrieve the repository code on this machine

      - name: Install Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven #Enable caching of Maven dependencies between runs, to speed up subsequent runs

      - name: Build and test with Maven
        run: ./mvnw clean verify